version: "3.8"
services:
  client:
    image: "react-frontend-image"
    container_name: "react-frontend-container"
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - dick-network
    volumes:
      - ./client:/app/client:cached
      - client_node_modules:/app/client/node_modules:delegated
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=3000
    command: "npm start"

  server:
    build: ./server
    image: "express-backend-image"
    container_name: "express-backend-container"
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - dick-network
    volumes:
      - ./server:/app/server:cached
      - server_node_modules:/app/server/node_modules:delegated
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_PORT=3001
    env_file:
      - ./server/.env

  database:
    image: mongo:latest
    container_name: mongo-db-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_PORT=27017
    volumes:
      - ./mongo-db-backup:/data/db
    networks:
      - dick-network

volumes:
  client_node_modules:
  server_node_modules:

networks:
  dick-network:
    driver: bridge