version: "3.8"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: "stinger222/express-backend-image:2.0"
    container_name: "express-backend-container-prod"
    restart: always
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge