version: "3.8"
services:
  client:
    image: "react-frontend-image-dev"
    container_name: "react-frontend-container"
    build: ./client
    # stdin_open: true  # May be needed to prevent "immediate exit" issue
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    volumes:
      - ./client:/app/client:cached
      - client_node_modules:/app/client/node_modules:delegated
    env_file:
      - ./client/config/.env.dev
    command: "npm run start -- --host"

  server:
    build: ./server
    image: "express-backend-image-dev"
    container_name: "express-backend-container"
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - ./server:/app/server:cached
      - server_node_modules:/app/server/node_modules:delegated
    env_file:
      - ./server/config/.env.dev

  database:
    image: mongo:latest
    container_name: mongo-db-container
    ports:
      - "27017:27017"
    environment:
      - MONGO_PORT=27017
    volumes:
      - ./mongo-db-backup:/data/db
    networks:
      - app-network

volumes:
  client_node_modules:
  server_node_modules:

networks:
  app-network:
    driver: bridge