FROM node:18-alpine AS build

WORKDIR /app/server

COPY package.json .
COPY package-lock.json .

RUN npm install --silent

COPY . .

RUN npm run build

FROM node:18-alpine

WORKDIR /app/server

COPY package*.json .
RUN npm install --only=prod

COPY --from=build /app/server/dist ./dist

EXPOSE 3001

CMD [ "npm", "run", "production" ]